# Generated by Django 5.1 on 2024-08-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_number', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('course_of_study', models.CharField(max_length=100)),
                ('year_of_study', models.IntegerField()),
                ('main_sport', models.CharField(max_length=50)),
                ('alternative_sport', models.CharField(blank=True, max_length=50, null=True)),
                ('playing_experience', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('current_club', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_information', models.CharField(max_length=100)),
                ('next_of_kin_name', models.CharField(max_length=100)),
                ('next_of_kin_contacts', models.CharField(max_length=100)),
                ('medical_info', models.TextField(blank=True, null=True)),
                ('signature', models.BinaryField(blank=True, null=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
