# Generated by Django 5.1 on 2024-08-26 22:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='medical_info',
            new_name='food_allergy',
        ),
        migrations.RemoveField(
            model_name='player',
            name='signature',
        ),
        migrations.AddField(
            model_name='player',
            name='A_Level_School',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='Hall_of_Residence',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='injury_history',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
